//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronicComponents.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Cart
    {
        public Cart(int iID)
        {
            electronicComponents1Entities1 db = new electronicComponents1Entities1();
            this.productID = iID;
            Product product = db.Products.Single(n => n.id == iID);
            this.name = product.name;
            this.imagee = product.image1;
            this.price = (decimal)product.promotionPrice;
            this.quantity = 1;
            this.total = price * quantity;
        }
        public Cart()
        {

        }
        public int id { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> memberID { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> total { get; set; }
        public string imagee { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
    }
}
