//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronicComponents.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderShips = new HashSet<OrderShip>();
        }
    
        public int id { get; set; }
        public string fullName { get; set; }
        public string addresss { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public Nullable<int> memberCategoryID { get; set; }
        public Nullable<bool> isMember { get; set; }
    
        public virtual MemberCategory MemberCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderShip> OrderShips { get; set; }
    }
}
