//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronicComponents.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCodeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscountCodeDetail()
        {
            this.MemberDiscountCodes = new HashSet<MemberDiscountCode>();
        }
    
        public int id { get; set; }
        public Nullable<int> discountCodeID { get; set; }
        public string code { get; set; }
        public Nullable<bool> isUsed { get; set; }
    
        public virtual DiscountCode DiscountCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberDiscountCode> MemberDiscountCodes { get; set; }
    }
}
