//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronicComponents.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscountCode()
        {
            this.DiscountCodeDetails = new HashSet<DiscountCodeDetail>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
        public Nullable<int> numberDiscount { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCodeDetail> DiscountCodeDetails { get; set; }
    }
}
