//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronicComponents.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.DiscountCodes = new HashSet<DiscountCode>();
            this.ImportCoupons = new HashSet<ImportCoupon>();
            this.QAs = new HashSet<QA>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
        public string passwordd { get; set; }
        public string fullName { get; set; }
        public string addresss { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string imagee { get; set; }
        public Nullable<int> employeeTypeID { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCode> DiscountCodes { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportCoupon> ImportCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QA> QAs { get; set; }
    }
}
